-- Databricks notebook source
-- MAGIC %md
-- MAGIC # Bank marketing campaign analysis - SQL pipeline (Databricks SQL)
-- MAGIC Generated by `scripts/build_databricks.py` from `sql/` (same Spark-dialect SQL that runs locally on DuckDB).
-- MAGIC
-- MAGIC 1. Upload the raw files to the Unity Catalog volume `/Volumes/workspace/da_learn_05/raw` (see `databricks/SETUP.md`).
-- MAGIC 2. Attach to a SQL warehouse (or DBR 13.3+ cluster) and *Run all*.
-- MAGIC 3. Cells: config -> staging (`read_files`) -> 02 cleaning -> 03 star schema -> 04 KPIs -> 05 data-quality -> visualization queries.

-- COMMAND ----------

-- Config: change catalog / schema here (and in the dashboard JSON) if needed
CREATE SCHEMA IF NOT EXISTS workspace.da_learn_05;
USE CATALOG workspace;
USE SCHEMA da_learn_05;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 01 Staging - all columns as STRING (`inferColumnTypes => false`), typing happens in 02

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_contacts AS
SELECT age, job, marital, education, `default` AS credit_default, housing, loan AS personal_loan, contact AS contact_channel, `month` AS contact_month, day_of_week, duration, campaign, pdays, previous, poutcome, `emp.var.rate` AS emp_var_rate, `cons.price.idx` AS cons_price_idx, `cons.conf.idx` AS cons_conf_idx, euribor3m, `nr.employed` AS nr_employed, y
FROM read_files('/Volumes/workspace/da_learn_05/raw/bank-additional-full.csv',
  format => 'csv', header => true, sep => ';', inferColumnTypes => false);

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 02 Cleaning (`sql/02_cleaning.sql`)

-- COMMAND ----------

-- 02_cleaning.sql  Typed, standardised, de-duplicated campaign contacts (Spark SQL dialect; DuckDB via 00 shims)

CREATE OR REPLACE TABLE cln_contacts_typed AS
SELECT
  TRY_CAST(trim(age) AS INT)                                          AS age,
  CASE WHEN lower(trim(job)) = 'admin.' THEN 'admin' ELSE lower(trim(job)) END AS job,
  lower(trim(marital))                                                AS marital,
  CASE lower(trim(education))
       WHEN 'basic.4y' THEN 'basic 4y' WHEN 'basic.6y' THEN 'basic 6y' WHEN 'basic.9y' THEN 'basic 9y'
       WHEN 'high.school' THEN 'high school' WHEN 'professional.course' THEN 'professional course'
       WHEN 'university.degree' THEN 'university degree' ELSE lower(trim(education)) END AS education,
  lower(trim(credit_default))                                         AS credit_default,
  lower(trim(housing))                                                AS housing_loan,
  lower(trim(personal_loan))                                          AS personal_loan,
  lower(trim(contact_channel))                                        AS contact_channel,
  CAST((instr('janfebmaraprmayjunjulaugsepoctnovdec', lower(trim(contact_month))) + 2) / 3 AS INT) AS month_num,
  lower(trim(contact_month))                                          AS month_abbr,
  CAST((instr('montuewedthufri', lower(trim(day_of_week))) + 2) / 3 AS INT) AS dow_num,
  lower(trim(day_of_week))                                            AS dow_abbr,
  TRY_CAST(trim(duration) AS INT)                                     AS duration_sec,
  TRY_CAST(trim(campaign) AS INT)                                     AS campaign_calls,
  TRY_CAST(trim(pdays) AS INT)                                        AS pdays_raw,
  TRY_CAST(trim(previous) AS INT)                                     AS previous_contacts,
  lower(trim(poutcome))                                               AS prev_outcome,
  TRY_CAST(trim(emp_var_rate) AS DOUBLE)                              AS emp_var_rate,
  TRY_CAST(trim(cons_price_idx) AS DOUBLE)                            AS cons_price_idx,
  TRY_CAST(trim(cons_conf_idx) AS DOUBLE)                             AS cons_conf_idx,
  TRY_CAST(trim(euribor3m) AS DOUBLE)                                 AS euribor3m,
  TRY_CAST(trim(nr_employed) AS DOUBLE)                               AS nr_employed,
  CASE WHEN lower(trim(y)) = 'yes' THEN 1 ELSE 0 END                  AS converted
FROM stg_contacts;

-- COMMAND ----------

-- The file has no client id: exact duplicate records (all 21 fields equal) are collapsed, then a deterministic


CREATE OR REPLACE TABLE cln_contacts_dedup AS
SELECT DISTINCT * FROM cln_contacts_typed
WHERE age IS NOT NULL AND campaign_calls IS NOT NULL AND month_num BETWEEN 1 AND 12 AND dow_num BETWEEN 1 AND 5;

-- COMMAND ----------

CREATE OR REPLACE TABLE cln_contacts AS
SELECT
  ROW_NUMBER() OVER (ORDER BY month_num, dow_num, age, job, marital, education, credit_default, housing_loan, personal_loan,
                              contact_channel, duration_sec, campaign_calls, pdays_raw, previous_contacts, prev_outcome,
                              emp_var_rate, cons_price_idx, cons_conf_idx, euribor3m, nr_employed, converted) AS contact_id,
  age,
  CASE WHEN age < 25 THEN '1: 17-24' WHEN age < 35 THEN '2: 25-34' WHEN age < 45 THEN '3: 35-44'
       WHEN age < 55 THEN '4: 45-54' WHEN age < 65 THEN '5: 55-64' ELSE '6: 65+' END AS age_band,
  job, marital, education, credit_default, housing_loan, personal_loan, contact_channel,
  month_num, concat(upper(substr(month_abbr, 1, 1)), substr(month_abbr, 2)) AS month_name,
  dow_num, concat(upper(substr(dow_abbr, 1, 1)), substr(dow_abbr, 2)) AS day_name,
  duration_sec,
  CASE WHEN duration_sec < 120 THEN '1: <2 min' WHEN duration_sec < 300 THEN '2: 2-5 min'
       WHEN duration_sec < 600 THEN '3: 5-10 min' ELSE '4: 10+ min' END AS call_length_band,
  campaign_calls,
  CASE WHEN campaign_calls = 1 THEN '1: 1 call' WHEN campaign_calls = 2 THEN '2: 2 calls'
       WHEN campaign_calls = 3 THEN '3: 3 calls' WHEN campaign_calls <= 5 THEN '4: 4-5 calls'
       WHEN campaign_calls <= 10 THEN '5: 6-10 calls' ELSE '6: 11+ calls' END AS calls_band,
  CASE WHEN pdays_raw = 999 THEN NULL ELSE pdays_raw END AS days_since_prev_campaign,
  previous_contacts,
  CASE WHEN previous_contacts > 0 THEN 1 ELSE 0 END AS was_previously_contacted,
  prev_outcome,
  emp_var_rate, cons_price_idx, cons_conf_idx, euribor3m, nr_employed,
  CASE WHEN euribor3m < 1 THEN '1: <1%' WHEN euribor3m < 1.5 THEN '2: 1-1.5%' WHEN euribor3m < 4 THEN '3: 1.5-4%'
       WHEN euribor3m < 4.9 THEN '4: 4-4.9%' ELSE '5: 4.9%+' END AS euribor_band,
  converted,
  CASE WHEN job = 'unknown' OR marital = 'unknown' OR education = 'unknown' THEN 1 ELSE 0 END AS dq_unknown_profile,
  CASE WHEN campaign_calls > 10 THEN 1 ELSE 0 END AS is_heavy_contact
FROM cln_contacts_dedup;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 03 Star schema (`sql/03_model.sql`)

-- COMMAND ----------

-- 03_model.sql  Star schema: fact_contact + dim_client (junk profile), dim_period (month x weekday),

CREATE OR REPLACE TABLE dim_client AS
SELECT ROW_NUMBER() OVER (ORDER BY age_band, job, marital, education, credit_default, housing_loan, personal_loan) AS client_key,
       age_band, job, marital, education, credit_default, housing_loan, personal_loan
FROM (SELECT DISTINCT age_band, job, marital, education, credit_default, housing_loan, personal_loan FROM cln_contacts) c;

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_period AS
SELECT month_num * 10 + dow_num AS period_key, month_num, month_name,
       CASE WHEN month_num <= 3 THEN 1 WHEN month_num <= 6 THEN 2 WHEN month_num <= 9 THEN 3 ELSE 4 END AS quarter,
       dow_num, day_name
FROM (SELECT DISTINCT month_num, month_name, dow_num, day_name FROM cln_contacts) p;

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_channel AS
SELECT ROW_NUMBER() OVER (ORDER BY contact_channel) AS channel_key, contact_channel,
       CASE WHEN contact_channel = 'cellular' THEN 'Mobile' ELSE 'Landline' END AS channel_label
FROM (SELECT DISTINCT contact_channel FROM cln_contacts) ch;

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_prev_campaign AS
SELECT ROW_NUMBER() OVER (ORDER BY prev_outcome) AS prev_key, prev_outcome,
       CASE WHEN prev_outcome = 'nonexistent' THEN 'Not in previous campaign'
            WHEN prev_outcome = 'failure' THEN 'Previous campaign: no'
            ELSE 'Previous campaign: yes' END AS prev_label
FROM (SELECT DISTINCT prev_outcome FROM cln_contacts) pc;

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_economy AS
SELECT ROW_NUMBER() OVER (ORDER BY euribor3m, emp_var_rate, cons_price_idx, cons_conf_idx, nr_employed) AS economy_key,
       emp_var_rate, cons_price_idx, cons_conf_idx, euribor3m, nr_employed, euribor_band
FROM (SELECT DISTINCT emp_var_rate, cons_price_idx, cons_conf_idx, euribor3m, nr_employed, euribor_band FROM cln_contacts) e;

-- COMMAND ----------

CREATE OR REPLACE TABLE fact_contact AS
SELECT
  c.contact_id, cl.client_key, c.month_num * 10 + c.dow_num AS period_key, ch.channel_key, pc.prev_key, e.economy_key,
  c.age, c.duration_sec, c.call_length_band, c.campaign_calls, c.calls_band, c.days_since_prev_campaign,
  c.previous_contacts, c.was_previously_contacted, c.converted, c.is_heavy_contact
FROM cln_contacts c
LEFT JOIN dim_client cl ON c.age_band = cl.age_band AND c.job = cl.job AND c.marital = cl.marital
                       AND c.education = cl.education AND c.credit_default = cl.credit_default
                       AND c.housing_loan = cl.housing_loan AND c.personal_loan = cl.personal_loan
LEFT JOIN dim_channel ch ON c.contact_channel = ch.contact_channel
LEFT JOIN dim_prev_campaign pc ON c.prev_outcome = pc.prev_outcome
LEFT JOIN dim_economy e ON c.euribor3m = e.euribor3m AND c.emp_var_rate = e.emp_var_rate
                       AND c.cons_price_idx = e.cons_price_idx AND c.cons_conf_idx = e.cons_conf_idx
                       AND c.nr_employed = e.nr_employed;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 04 Business KPIs (`sql/04_analysis.sql`)

-- COMMAND ----------

-- 04_analysis.sql  Business KPIs (Spark SQL dialect)

CREATE OR REPLACE TABLE a_kpi_headline AS
SELECT
  COUNT(*)                                                                   AS contacts,
  SUM(converted)                                                             AS conversions,
  ROUND(100.0 * SUM(converted) / COUNT(*), 2)                                AS conversion_rate_pct,
  SUM(campaign_calls)                                                        AS total_calls,
  ROUND(AVG(campaign_calls), 2)                                              AS avg_calls_per_client,
  ROUND(SUM(campaign_calls) / SUM(converted), 2)                             AS calls_per_conversion,
  ROUND(SUM(duration_sec) / 3600.0, 1)                                       AS last_call_talk_hours,
  ROUND(median(duration_sec), 0)                                             AS median_last_call_sec,
  ROUND(100.0 * SUM(was_previously_contacted) / COUNT(*), 2)                 AS pct_previously_contacted,
  ROUND(100.0 * SUM(CASE WHEN contact_channel = 'cellular' THEN 1 ELSE 0 END) / COUNT(*), 2) AS pct_mobile,
  ROUND(100.0 * SUM(CASE WHEN month_num = 5 THEN 1 ELSE 0 END) / COUNT(*), 2) AS pct_contacts_in_may
FROM cln_contacts;

-- COMMAND ----------

-- Q1: Which client segments convert best, and what does a conversion cost in calls? (one table, many attributes)


CREATE OR REPLACE TABLE a_conv_by_segment AS
WITH base AS (SELECT 100.0 * SUM(converted) / COUNT(*) AS overall_rate FROM cln_contacts),
seg AS (
  SELECT 'age_band' AS attribute, age_band AS value, COUNT(*) AS contacts, SUM(converted) AS conversions, SUM(campaign_calls) AS calls FROM cln_contacts GROUP BY age_band
  UNION ALL SELECT 'job', job, COUNT(*), SUM(converted), SUM(campaign_calls) FROM cln_contacts GROUP BY job
  UNION ALL SELECT 'education', education, COUNT(*), SUM(converted), SUM(campaign_calls) FROM cln_contacts GROUP BY education
  UNION ALL SELECT 'marital', marital, COUNT(*), SUM(converted), SUM(campaign_calls) FROM cln_contacts GROUP BY marital
  UNION ALL SELECT 'housing_loan', housing_loan, COUNT(*), SUM(converted), SUM(campaign_calls) FROM cln_contacts GROUP BY housing_loan
  UNION ALL SELECT 'personal_loan', personal_loan, COUNT(*), SUM(converted), SUM(campaign_calls) FROM cln_contacts GROUP BY personal_loan
  UNION ALL SELECT 'credit_default', credit_default, COUNT(*), SUM(converted), SUM(campaign_calls) FROM cln_contacts GROUP BY credit_default
)
SELECT s.attribute, s.value, s.contacts, s.conversions,
       ROUND(100.0 * s.conversions / s.contacts, 2)                        AS conversion_rate_pct,
       ROUND(100.0 * s.conversions / s.contacts / b.overall_rate, 2)       AS lift,
       ROUND(1.0 * s.calls / NULLIF(s.conversions, 0), 2)                  AS calls_per_conversion
FROM seg s CROSS JOIN base b;

-- COMMAND ----------

CREATE OR REPLACE TABLE a_conv_by_job AS
SELECT value AS job, contacts, conversions, conversion_rate_pct, lift, calls_per_conversion
FROM a_conv_by_segment WHERE attribute = 'job';

-- COMMAND ----------

CREATE OR REPLACE TABLE a_conv_by_age AS
SELECT value AS age_band, contacts, conversions, conversion_rate_pct, lift, calls_per_conversion
FROM a_conv_by_segment WHERE attribute = 'age_band';

-- COMMAND ----------

-- Q2: Diminishing returns - how does conversion change with the number of calls made to the same client?


CREATE OR REPLACE TABLE a_conv_by_calls AS
SELECT calls_band, COUNT(*) AS contacts, SUM(converted) AS conversions,
       ROUND(100.0 * SUM(converted) / COUNT(*), 2)                         AS conversion_rate_pct,
       SUM(campaign_calls)                                                 AS calls,
       ROUND(1.0 * SUM(campaign_calls) / NULLIF(SUM(converted), 0), 2)     AS calls_per_conversion,
       ROUND(100.0 * SUM(campaign_calls) / (SELECT SUM(campaign_calls) FROM cln_contacts), 2) AS share_of_calls_pct,
       ROUND(100.0 * SUM(converted) / (SELECT SUM(converted) FROM cln_contacts), 2)          AS share_of_conversions_pct
FROM cln_contacts GROUP BY calls_band;

-- COMMAND ----------

-- Q3: Does the previous campaign outcome predict this one?


CREATE OR REPLACE TABLE a_conv_by_prev_outcome AS
SELECT p.prev_label, COUNT(*) AS contacts, SUM(f.converted) AS conversions,
       ROUND(100.0 * SUM(f.converted) / COUNT(*), 2) AS conversion_rate_pct,
       ROUND(1.0 * SUM(f.campaign_calls) / NULLIF(SUM(f.converted), 0), 2) AS calls_per_conversion
FROM fact_contact f JOIN dim_prev_campaign p ON f.prev_key = p.prev_key
GROUP BY p.prev_label;

-- COMMAND ----------

-- Q4: Timing and channel - month, weekday, mobile vs landline


CREATE OR REPLACE TABLE a_conv_by_month AS
SELECT d.month_num, d.month_name, COUNT(*) AS contacts, SUM(f.converted) AS conversions,
       ROUND(100.0 * SUM(f.converted) / COUNT(*), 2) AS conversion_rate_pct,
       ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM fact_contact), 2) AS share_of_contacts_pct
FROM fact_contact f JOIN dim_period d ON f.period_key = d.period_key
GROUP BY d.month_num, d.month_name;

-- COMMAND ----------

CREATE OR REPLACE TABLE a_conv_by_weekday AS
SELECT d.dow_num, d.day_name, COUNT(*) AS contacts,
       ROUND(100.0 * SUM(f.converted) / COUNT(*), 2) AS conversion_rate_pct
FROM fact_contact f JOIN dim_period d ON f.period_key = d.period_key
GROUP BY d.dow_num, d.day_name;

-- COMMAND ----------

CREATE OR REPLACE TABLE a_conv_by_channel AS
SELECT ch.channel_label, COUNT(*) AS contacts, SUM(f.converted) AS conversions,
       ROUND(100.0 * SUM(f.converted) / COUNT(*), 2) AS conversion_rate_pct,
       ROUND(AVG(f.campaign_calls), 2) AS avg_calls,
       ROUND(1.0 * SUM(f.campaign_calls) / NULLIF(SUM(f.converted), 0), 2) AS calls_per_conversion
FROM fact_contact f JOIN dim_channel ch ON f.channel_key = ch.channel_key
GROUP BY ch.channel_label;

-- COMMAND ----------

-- Q5: Economic context - conversion vs the 3-month Euribor rate at contact time


CREATE OR REPLACE TABLE a_conv_by_economy AS
SELECT e.euribor_band, COUNT(*) AS contacts, SUM(f.converted) AS conversions,
       ROUND(100.0 * SUM(f.converted) / COUNT(*), 2) AS conversion_rate_pct,
       ROUND(AVG(e.euribor3m), 3) AS avg_euribor3m,
       ROUND(AVG(e.nr_employed), 0) AS avg_nr_employed,
       ROUND(AVG(e.cons_conf_idx), 1) AS avg_consumer_confidence
FROM fact_contact f JOIN dim_economy e ON f.economy_key = e.economy_key
GROUP BY e.euribor_band;

-- COMMAND ----------

-- Q6: Call length of the last contact (descriptive only: known after the call, not usable for targeting)


CREATE OR REPLACE TABLE a_conv_by_call_length AS
SELECT call_length_band, COUNT(*) AS contacts,
       ROUND(100.0 * SUM(converted) / COUNT(*), 2) AS conversion_rate_pct,
       ROUND(AVG(duration_sec), 0) AS avg_duration_sec
FROM fact_contact GROUP BY call_length_band;

-- COMMAND ----------

-- Q7: Targeting matrix - age band x channel, and the best/worst segments to call first


CREATE OR REPLACE TABLE a_age_channel_matrix AS
SELECT cl.age_band, ch.channel_label, COUNT(*) AS contacts,
       ROUND(100.0 * SUM(f.converted) / COUNT(*), 2) AS conversion_rate_pct
FROM fact_contact f JOIN dim_client cl ON f.client_key = cl.client_key JOIN dim_channel ch ON f.channel_key = ch.channel_key
GROUP BY cl.age_band, ch.channel_label;

-- COMMAND ----------

CREATE OR REPLACE TABLE a_target_segments AS
SELECT cl.job, cl.age_band, COUNT(*) AS contacts, SUM(f.converted) AS conversions,
       ROUND(100.0 * SUM(f.converted) / COUNT(*), 2) AS conversion_rate_pct,
       ROUND(1.0 * SUM(f.campaign_calls) / NULLIF(SUM(f.converted), 0), 2) AS calls_per_conversion
FROM fact_contact f JOIN dim_client cl ON f.client_key = cl.client_key
GROUP BY cl.job, cl.age_band
HAVING COUNT(*) >= 300;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 05 Data-quality checks (`sql/05_quality_checks.sql`)

-- COMMAND ----------

-- 05_quality_checks.sql  Data-quality evidence (Spark SQL dialect): before/after counts, unknown rates, issues, assertions

CREATE OR REPLACE TABLE dq_row_counts AS
SELECT 'contacts' AS entity, (SELECT COUNT(*) FROM stg_contacts) AS raw_rows,
       (SELECT COUNT(*) FROM cln_contacts_dedup) AS distinct_records,
       (SELECT COUNT(*) FROM cln_contacts) AS clean_rows, 'client contact (last call of campaign)' AS grain
UNION ALL SELECT 'fact_contact', NULL, NULL, (SELECT COUNT(*) FROM fact_contact), 'contact'
UNION ALL SELECT 'dim_client', NULL, NULL, (SELECT COUNT(*) FROM dim_client), 'age band x job x marital x education x credit flags'
UNION ALL SELECT 'dim_period', NULL, NULL, (SELECT COUNT(*) FROM dim_period), 'month x weekday'
UNION ALL SELECT 'dim_channel', NULL, NULL, (SELECT COUNT(*) FROM dim_channel), 'contact channel'
UNION ALL SELECT 'dim_prev_campaign', NULL, NULL, (SELECT COUNT(*) FROM dim_prev_campaign), 'previous campaign outcome'
UNION ALL SELECT 'dim_economy', NULL, NULL, (SELECT COUNT(*) FROM dim_economy), 'macro indicator snapshot';

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_null_rates AS
SELECT 'contacts' AS entity, 'job' AS column_name,
  (SELECT ROUND(100.0 * SUM(CASE WHEN job IS NULL OR trim(job) IN ('', 'unknown') THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_contacts) AS raw_unknown_pct,
  (SELECT ROUND(100.0 * SUM(CASE WHEN job = 'unknown' THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_contacts) AS clean_unknown_pct,
  'kept as category unknown' AS treatment
UNION ALL SELECT 'contacts', 'education',
  (SELECT ROUND(100.0 * SUM(CASE WHEN education IS NULL OR trim(education) IN ('', 'unknown') THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_contacts),
  (SELECT ROUND(100.0 * SUM(CASE WHEN education = 'unknown' THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_contacts),
  'kept as category unknown'
UNION ALL SELECT 'contacts', 'credit_default',
  (SELECT ROUND(100.0 * SUM(CASE WHEN credit_default IS NULL OR trim(credit_default) IN ('', 'unknown') THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_contacts),
  (SELECT ROUND(100.0 * SUM(CASE WHEN credit_default = 'unknown' THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_contacts),
  'kept as category unknown (bank did not disclose)'
UNION ALL SELECT 'contacts', 'housing_loan',
  (SELECT ROUND(100.0 * SUM(CASE WHEN housing IS NULL OR trim(housing) IN ('', 'unknown') THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_contacts),
  (SELECT ROUND(100.0 * SUM(CASE WHEN housing_loan = 'unknown' THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_contacts),
  'kept as category unknown'
UNION ALL SELECT 'contacts', 'pdays (999 = not previously contacted)',
  (SELECT ROUND(100.0 * SUM(CASE WHEN trim(pdays) = '999' THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_contacts),
  (SELECT ROUND(100.0 * SUM(CASE WHEN days_since_prev_campaign IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_contacts),
  'sentinel 999 -> NULL';

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_issues AS
SELECT 'contacts: exact duplicate records removed' AS check_name,
       (SELECT COUNT(*) FROM stg_contacts) - (SELECT COUNT(*) FROM cln_contacts) AS affected_rows
UNION ALL SELECT 'contacts: unknown job / marital / education (kept)', (SELECT SUM(dq_unknown_profile) FROM cln_contacts)
UNION ALL SELECT 'contacts: credit_default = yes (too rare to analyse)', (SELECT COUNT(*) FROM cln_contacts WHERE credit_default = 'yes')
UNION ALL SELECT 'contacts: last call duration 0 sec', (SELECT COUNT(*) FROM cln_contacts WHERE duration_sec = 0)
UNION ALL SELECT 'contacts: more than 10 calls in campaign (kept, flagged)', (SELECT SUM(is_heavy_contact) FROM cln_contacts)
UNION ALL SELECT 'contacts: previously contacted but pdays = 999', (SELECT COUNT(*) FROM cln_contacts WHERE previous_contacts > 0 AND days_since_prev_campaign IS NULL)
UNION ALL SELECT 'RI: fact without client profile', (SELECT COUNT(*) FROM fact_contact WHERE client_key IS NULL)
UNION ALL SELECT 'RI: fact without channel', (SELECT COUNT(*) FROM fact_contact WHERE channel_key IS NULL)
UNION ALL SELECT 'RI: fact without previous-campaign outcome', (SELECT COUNT(*) FROM fact_contact WHERE prev_key IS NULL)
UNION ALL SELECT 'RI: fact without economy snapshot', (SELECT COUNT(*) FROM fact_contact WHERE economy_key IS NULL);

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_assertions AS
WITH c AS (
  SELECT 'fact_contact.contact_id unique' AS check_name, (SELECT COUNT(*) - COUNT(DISTINCT contact_id) FROM fact_contact) AS failed_rows
  UNION ALL SELECT 'fact_contact.client_key -> dim_client', (SELECT COUNT(*) FROM fact_contact WHERE client_key IS NULL OR client_key NOT IN (SELECT client_key FROM dim_client))
  UNION ALL SELECT 'fact_contact.period_key -> dim_period', (SELECT COUNT(*) FROM fact_contact WHERE period_key NOT IN (SELECT period_key FROM dim_period))
  UNION ALL SELECT 'fact_contact.channel_key -> dim_channel', (SELECT COUNT(*) FROM fact_contact WHERE channel_key IS NULL OR channel_key NOT IN (SELECT channel_key FROM dim_channel))
  UNION ALL SELECT 'fact_contact.prev_key -> dim_prev_campaign', (SELECT COUNT(*) FROM fact_contact WHERE prev_key IS NULL OR prev_key NOT IN (SELECT prev_key FROM dim_prev_campaign))
  UNION ALL SELECT 'fact_contact.economy_key -> dim_economy', (SELECT COUNT(*) FROM fact_contact WHERE economy_key IS NULL OR economy_key NOT IN (SELECT economy_key FROM dim_economy))
  UNION ALL SELECT 'every raw month and weekday parsed', (SELECT COUNT(*) FROM cln_contacts_typed WHERE month_num NOT BETWEEN 1 AND 12 OR dow_num NOT BETWEEN 1 AND 5)
  UNION ALL SELECT 'target y is yes or no', (SELECT COUNT(*) FROM stg_contacts WHERE lower(trim(y)) NOT IN ('yes', 'no'))
  UNION ALL SELECT 'age between 17 and 98', (SELECT COUNT(*) FROM fact_contact WHERE age < 17 OR age > 98)
  UNION ALL SELECT 'at least one call per contact', (SELECT COUNT(*) FROM fact_contact WHERE campaign_calls < 1)
  UNION ALL SELECT 'no previous contacts implies outcome nonexistent', (SELECT COUNT(*) FROM cln_contacts WHERE previous_contacts = 0 AND prev_outcome <> 'nonexistent')
  UNION ALL SELECT 'previous success implies previous contacts > 0', (SELECT COUNT(*) FROM cln_contacts WHERE prev_outcome = 'success' AND previous_contacts = 0)
  UNION ALL SELECT 'segment conversions add up to total', (SELECT COUNT(*) FROM (SELECT attribute, SUM(conversions) AS s FROM a_conv_by_segment GROUP BY attribute) x
                                                           WHERE s <> (SELECT conversions FROM a_kpi_headline))
  UNION ALL SELECT 'one call converts better than 6+ calls', (SELECT COUNT(*) FROM a_conv_by_calls a JOIN a_conv_by_calls b
                                                              ON a.calls_band = '1: 1 call' AND b.calls_band IN ('5: 6-10 calls', '6: 11+ calls')
                                                              WHERE b.conversion_rate_pct >= a.conversion_rate_pct)
)
SELECT check_name, failed_rows, CASE WHEN failed_rows = 0 THEN 'PASS' ELSE 'FAIL' END AS status FROM c;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Quality summary
-- MAGIC All assertions should be PASS.

-- COMMAND ----------

SELECT * FROM dq_row_counts ORDER BY entity;

-- COMMAND ----------

SELECT * FROM dq_assertions ORDER BY status, check_name;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Visualizations
-- MAGIC Run each cell, click **+ > Visualization** and configure as described. The same views are pre-built in `marketing_campaign_dashboard.lvdash.json`.

-- COMMAND ----------

SELECT * FROM a_kpi_headline;

-- COMMAND ----------

-- Visualization: Diminishing returns of repeat calls
-- Bar: X = calls_band, Y = conversion_rate_pct (tooltip calls_per_conversion)
SELECT calls_band, contacts, conversion_rate_pct, calls_per_conversion, share_of_conversions_pct FROM a_conv_by_calls ORDER BY calls_band;

-- COMMAND ----------

-- Visualization: Previous campaign outcome
-- Horizontal bar: Y = prev_label, X = conversion_rate_pct
SELECT prev_label, contacts, conversion_rate_pct, calls_per_conversion FROM a_conv_by_prev_outcome ORDER BY conversion_rate_pct DESC;

-- COMMAND ----------

-- Visualization: Conversion by age band
-- Bar: X = age_band, Y = conversion_rate_pct
SELECT age_band, contacts, conversion_rate_pct, lift, calls_per_conversion FROM a_conv_by_age ORDER BY age_band;

-- COMMAND ----------

-- Visualization: Conversion by job
-- Horizontal bar: Y = job, X = conversion_rate_pct
SELECT job, contacts, conversion_rate_pct, calls_per_conversion FROM a_conv_by_job ORDER BY conversion_rate_pct DESC;

-- COMMAND ----------

-- Visualization: Conversion by month
-- Bar: X = month_name (sorted by month_num), Y = conversion_rate_pct; second axis share_of_contacts_pct
SELECT month_num, month_name, contacts, conversion_rate_pct, share_of_contacts_pct FROM a_conv_by_month ORDER BY month_num;

-- COMMAND ----------

-- Visualization: Age band x channel
-- Grouped bar: X = age_band, Y = conversion_rate_pct, color = channel_label
SELECT age_band, channel_label, contacts, conversion_rate_pct FROM a_age_channel_matrix ORDER BY age_band, channel_label;

-- COMMAND ----------

-- Visualization: Economic context
-- Bar: X = euribor_band, Y = conversion_rate_pct
SELECT euribor_band, contacts, conversion_rate_pct, avg_euribor3m FROM a_conv_by_economy ORDER BY euribor_band;
