#!/usr/bin/env python3
"""Generate the Databricks SQL notebook (databricks/<notebook>.sql) from sql/02-05 and, with --with-dashboard,
the Lakeview dashboard JSON from scripts/dashboard_def.py. Settings come from pipeline.json ("databricks")."""
import json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
CFG = json.loads((ROOT / "pipeline.json").read_text())
D = CFG["databricks"]
CATALOG, SCHEMA = D["catalog"], D["schema"]
VOLUME = f"/Volumes/{CATALOG}/{SCHEMA}/raw"
SEP = "\n\n-- COMMAND ----------\n\n"


def md(text):
    return "\n".join(["-- MAGIC %md"] + [f"-- MAGIC {l}".rstrip() for l in text.strip().splitlines()])


def statements(path):
    out, buf = [], []
    for line in path.read_text().splitlines():
        buf.append(line)
        code = line.split("--")[0] if ("--" in line and line[:line.find("--")].count("'") % 2 == 0) else line
        if code.rstrip().endswith(";"):
            keep = [l for l in buf if not l.strip().startswith("--")]
            head = next((l for l in buf if l.strip().startswith("--")), None)
            out.append("\n".join(([head] if head else []) + keep).strip()); buf = []
    return out


def notebook():
    import dashboard_def
    cells = ["-- Databricks notebook source\n" + md(f"""
# {D['title']} - SQL pipeline (Databricks SQL)
Generated by `scripts/build_databricks.py` from `sql/` (same Spark-dialect SQL that runs locally on DuckDB).

1. Upload the raw files to the Unity Catalog volume `{VOLUME}` (see `databricks/SETUP.md`).
2. Attach to a SQL warehouse (or DBR 13.3+ cluster) and *Run all*.
3. Cells: config -> staging (`read_files`) -> 02 cleaning -> 03 star schema -> 04 KPIs -> 05 data-quality -> visualization queries.""")]
    cells.append(f"-- Config: change catalog / schema here (and in the dashboard JSON) if needed\nCREATE SCHEMA IF NOT EXISTS {CATALOG}.{SCHEMA};\nUSE CATALOG {CATALOG};\nUSE SCHEMA {SCHEMA};")
    cells.append(md("## 01 Staging - all columns as STRING (`inferColumnTypes => false`), typing happens in 02"))
    for t, spec in D["staging"].items():
        opts = spec.get("options", "header => true, multiLine => true, escape => '\"'")
        cols = spec.get("select", "*")
        cells.append(f"CREATE OR REPLACE TABLE {t} AS\nSELECT {cols}\nFROM read_files('{VOLUME}/{spec['file']}',\n  format => 'csv', {opts}, inferColumnTypes => false);")
    titles = {"02_cleaning.sql": "02 Cleaning", "03_model.sql": "03 Star schema", "04_analysis.sql": "04 Business KPIs",
              "05_quality_checks.sql": "05 Data-quality checks"}
    for f, title in titles.items():
        cells.append(md(f"## {title} (`sql/{f}`)"))
        cells += statements(ROOT / "sql" / f)
    cells.append(md("## Quality summary\nAll assertions should be PASS."))
    cells.append("SELECT * FROM dq_row_counts ORDER BY entity;")
    cells.append("SELECT * FROM dq_assertions ORDER BY status, check_name;")
    cells.append(md(f"## Visualizations\nRun each cell, click **+ > Visualization** and configure as described. The same views are pre-built in `{D['dashboard_file']}`."))
    cells.append("SELECT * FROM a_kpi_headline;")
    for title, how, q in dashboard_def.VIZ:
        cells.append(f"-- Visualization: {title}\n-- {how}\n{q};")
    return SEP.join(cells) + "\n"


if __name__ == "__main__":
    out = ROOT / "databricks"; out.mkdir(exist_ok=True)
    (out / f"{D['notebook']}.sql").write_text(notebook())
    if "--with-dashboard" in sys.argv:
        import dashboard_def
        (out / D["dashboard_file"]).write_text(json.dumps(dashboard_def.dashboard(f"{CATALOG}.{SCHEMA}"), indent=1) + "\n")
    print("wrote", sorted(p.name for p in out.iterdir() if p.is_file()))
